# Copyright (c) AnticliMaxtic
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
        args: ["--diff"]
        files: \.(tf|tfvars)$

  - repo: local
    hooks:
      - id: copywrite-headers
        name: Copywrite Headers
        entry: go run github.com/hashicorp/copywrite headers -d . --config .copywrite.hcl
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual, pre-commit]
      - id: generate-docs
        name: Generate Terraform Provider Docs
        entry: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs generate --provider-dir . -provider-name hex
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual, pre-commit]
